package dast.scan

/** Self-contained, read-only HTML view of a scan (Tier-1 reporting): the same
  * findings the JSON report carries, plus the opt-in evidence transcript, in one
  * file you can open in a browser or hand to someone. No server, no new trust
  * model -- it only renders output the scan already produced.
  *
  * Input is the parsed [[FindingsReport]] JSON (either the single-target shape
  * `{target, findingCount, findings}` or the site shape `{seed, findingCount,
  * pages}`) and the evidence records ([[dast.EvidenceLog]] lines, possibly
  * empty). All rendering is pure and unit tested; the file write lives in
  * [[ScanMain]].
  */
object ReportHtml:

  /** Render the whole report (findings + evidence) as one HTML document. */
  def render(report: ujson.Value, evidence: Seq[ujson.Value] = Nil): String =
    val o = report.objOpt.getOrElse(scala.collection.mutable.LinkedHashMap.empty[String, ujson.Value])
    val isSite = o.contains("pages")
    val title = o.get("seed").orElse(o.get("target")).flatMap(_.strOpt)
      .getOrElse("scan")
    val count = o.get("findingCount").flatMap(_.numOpt).map(_.toInt)
      .getOrElse(0)
    val body =
      if isSite then sitePages(o.get("pages").flatMap(_.arrOpt).map(_.toSeq).getOrElse(Nil))
      else findingsList(o.get("findings").flatMap(_.arrOpt).map(_.toSeq).getOrElse(Nil))
    s"""<!doctype html>
       |<html lang="en"><head><meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>DAST report — ${esc(title)}</title>
       |<style>$Css</style></head>
       |<body>
       |<header><h1>DAST report</h1>
       |<div class="meta"><span class="tgt">${esc(title)}</span>
       |<span class="count">$count finding${if count == 1 then "" else "s"}</span></div>
       |</header>
       |<main>
       |$body
       |${evidenceSection(evidence)}
       |</main>
       |<footer>Generated by pekko-dast — findings are deterministically confirmed; replay handles reconstruct each one without the model.</footer>
       |</body></html>""".stripMargin

  /** Site report: one section per scanned URL. */
  private def sitePages(pages: Seq[ujson.Value]): String =
    if pages.isEmpty then emptyState
    else pages.map { p =>
      val po = p.objOpt.getOrElse(scala.collection.mutable.LinkedHashMap.empty[String, ujson.Value])
      val url = po.get("url").flatMap(_.strOpt).getOrElse("")
      val fs = po.get("findings").flatMap(_.arrOpt).map(_.toSeq).getOrElse(Nil)
      s"""<section class="page"><h2>${esc(url)}</h2>
         |${findingsList(fs)}</section>""".stripMargin
    }.mkString("\n")

  private def findingsList(findings: Seq[ujson.Value]): String =
    if findings.isEmpty then emptyState
    else findings.map(findingCard).mkString("\n")

  private def findingCard(f: ujson.Value): String =
    val o = f.objOpt.getOrElse(scala.collection.mutable.LinkedHashMap.empty[String, ujson.Value])
    val kind = o.get("kind").flatMap(_.strOpt).getOrElse("")
    val sev = o.get("severity").flatMap(_.strOpt).getOrElse("Info")
    val evidence = o.get("evidence").flatMap(_.strOpt).getOrElse("")
    val repro = o.get("reproducible").flatMap(_.boolOpt).getOrElse(false)
    val replay = o.get("replay").flatMap(_.strOpt).getOrElse("")
    val reproBadge =
      if repro then """<span class="repro" title="deterministically confirmed">confirmed</span>"""
      else """<span class="guess" title="not deterministically confirmed">unconfirmed</span>"""
    s"""<article class="finding sev-${sev.toLowerCase}">
       |<div class="fhead"><span class="kind">${esc(kind)}</span>
       |<span class="sev">${esc(sev)}</span>$reproBadge</div>
       |<p class="ev">${esc(evidence)}</p>
       |${if replay.nonEmpty then s"""<pre class="replay"><span class="lbl">replay</span><code>${esc(replay)}</code></pre>""" else ""}
       |</article>""".stripMargin

  /** The evidence transcript: HTTP acts and model decisions, if any. */
  private def evidenceSection(evidence: Seq[ujson.Value]): String =
    if evidence.isEmpty then ""
    else
      val rows = evidence.map { e =>
        val o = e.objOpt.getOrElse(scala.collection.mutable.LinkedHashMap.empty[String, ujson.Value])
        o.get("kind").flatMap(_.strOpt).getOrElse("") match
          case "http" =>
            val m = field(o, "method"); val u = field(o, "url")
            val s = o.get("status").flatMap(_.numOpt).map(_.toInt.toString)
              .getOrElse("")
            val ms = o.get("ms").flatMap(_.numOpt).map(n => f"${n}%.0f ms")
              .getOrElse("")
            s"""<tr><td>${esc(field(o, "check"))}</td><td class="mono">${esc(m)}</td>
               |<td class="mono url">${esc(u)}</td><td class="st-${statusClass(s)}">$s</td>
               |<td class="num">$ms</td></tr>""".stripMargin
          case "decision" =>
            val conf = o.get("confirmed").flatMap(_.boolOpt).getOrElse(false)
            s"""<tr class="dec"><td>${esc(field(o, "check"))}</td>
               |<td colspan="2">decision @ ${esc(field(o, "point"))}: <b>${esc(field(o, "choice"))}</b></td>
               |<td colspan="2">${if conf then "confirmed" else "not confirmed"}</td></tr>""".stripMargin
          case _ => ""
      }.mkString("\n")
      s"""<section class="evidence"><h2>Evidence transcript<span class="sub">${evidence.size} record(s)</span></h2>
         |<table><thead><tr><th>check</th><th>method</th><th>url / detail</th><th>status</th><th>time</th></tr></thead>
         |<tbody>$rows</tbody></table></section>""".stripMargin

  private def field(
      o: scala.collection.Map[String, ujson.Value],
      k: String,
  ): String = o.get(k).flatMap(_.strOpt).getOrElse("")

  private def statusClass(s: String): String =
    s.headOption match
      case Some('2') => "ok"
      case Some('3') => "redir"
      case Some('4') | Some('5') => "err"
      case _ => "na"

  private val emptyState =
    """<p class="empty">No findings.</p>"""

  /** HTML-escape (the evidence/findings strings are app-controlled but may carry
    * markup-significant characters from the target's responses).
    */
  private def esc(s: String): String = s
    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    .replace("\"", "&quot;")

  private val Css =
    """:root{--bg:#0f1115;--card:#181b22;--ln:#262b36;--fg:#e6e8ee;--mut:#9aa3b2;--ac:#5b8cff}
      |*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg)}
      |header{padding:24px 28px;border-bottom:1px solid var(--ln)}h1{margin:0;font-size:20px}
      |.meta{margin-top:6px;color:var(--mut);display:flex;gap:14px;align-items:center}
      |.tgt{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--fg)}
      |.count{background:var(--card);border:1px solid var(--ln);border-radius:999px;padding:2px 10px;font-size:13px}
      |main{padding:20px 28px;max-width:1100px}
      |h2{font-size:15px;color:var(--mut);font-weight:600;margin:26px 0 10px;display:flex;gap:10px;align-items:baseline}
      |.sub{font-weight:400;font-size:12px}
      |.page{border-left:2px solid var(--ln);padding-left:16px;margin-bottom:8px}
      |.finding{background:var(--card);border:1px solid var(--ln);border-left-width:4px;border-radius:8px;padding:14px 16px;margin:10px 0}
      |.fhead{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
      |.kind{font-weight:600}.sev{font-size:12px;text-transform:uppercase;letter-spacing:.04em;padding:1px 8px;border-radius:4px}
      |.sev-critical{border-left-color:#ff4d6d}.sev-critical .sev{background:#ff4d6d;color:#1a0008}
      |.sev-high{border-left-color:#ff7849}.sev-high .sev{background:#ff7849;color:#1a0600}
      |.sev-medium{border-left-color:#ffc857}.sev-medium .sev{background:#ffc857;color:#1a1300}
      |.sev-low{border-left-color:#5b8cff}.sev-low .sev{background:#5b8cff;color:#00081a}
      |.sev-info{border-left-color:#5f6b7e}.sev-info .sev{background:#5f6b7e;color:#fff}
      |.repro{font-size:11px;color:#7ee787;border:1px solid #2ea04326;background:#2ea04314;padding:1px 7px;border-radius:4px}
      |.guess{font-size:11px;color:var(--mut);border:1px solid var(--ln);padding:1px 7px;border-radius:4px}
      |.ev{margin:10px 0 8px}
      |.replay{background:#0b0d11;border:1px solid var(--ln);border-radius:6px;padding:8px 10px;margin:0;overflow-x:auto;display:flex;gap:10px;align-items:center}
      |.replay .lbl{color:var(--mut);font-size:11px;text-transform:uppercase}
      |.replay code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;color:#8be9fd;white-space:pre}
      |.empty{color:var(--mut)}
      |.evidence table{width:100%;border-collapse:collapse;font-size:13px}
      |.evidence th{text-align:left;color:var(--mut);font-weight:500;border-bottom:1px solid var(--ln);padding:6px 8px}
      |.evidence td{border-bottom:1px solid var(--ln);padding:6px 8px;vertical-align:top}
      |.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.url{word-break:break-all}
      |.num{text-align:right;color:var(--mut);white-space:nowrap}
      |.st-ok{color:#7ee787}.st-redir{color:#ffc857}.st-err{color:#ff7849}.st-na{color:var(--mut)}
      |.dec td{color:var(--mut)}.dec b{color:var(--fg)}
      |footer{padding:18px 28px;color:var(--mut);font-size:12px;border-top:1px solid var(--ln);max-width:1100px}""".stripMargin
